# 코드가 push될 때 마다 실행되도록 하는 일련의 명령어들을 자동으로 실행하도록 하는 workflow 

# 전체적인 과정은 다음과 같다.
# 1. push된 코드를 확인한다. 
# 2. bats라는 testing FW를 설치한다. 
# 3. 잘 설치되었는지 확인하기 위해 bats의 버전 값을 확인한다. 

name: learn-github-actions
run-name: ${{ github.actor }} is learning GitHub Actions
on: [push] # 여기서는 push라는 이벤트가 발생할 때 workflow가 실행되도록 함 
jobs: # learn-github-actions라는 workflow에서 실행되는 모든 job의 그룹 
  check-bats-version: # job의 이름이 check-bats-version 
    runs-on: ubuntu-latest # GitHub에 의해 호스팅된 가상머신 위에서 실행된다는 걸 확인할 수 있다. 여기서는 최신 버전의 ubuntu에서 실행되도록 했다. 
    steps:
      - uses: actions/checkout@v4 # actions/checkout이라는 action이 있는데 그 action의 v4를 실행시킨다는 뜻 
                                  # checkout action은 반드시 사용해야 한다. 
      - uses: actions/setup-node@v3 # actions/setup-node@v3 이라는 action을 사용한다. 
        with:
          node-version: '14' # 이를 통해 Node.js 버전 14를 설치해서 node, npm이라는 명령어를 사용할 수 있도록 했다. 
      - run: npm install -g bats # npm 명령어 사용
      - run: bats -v # bats 버전 확인 

